### ISSUE TITLE
Logo text being covered by MLH Logo

### ISSUE THREAD

**Issue by CFarzaneh** [HackFSU/hackfsu_com#68] opened 2018-01-26 02:28 UTC
<img width="497" alt="screen shot 2018-01-25 at 21 25 37" src="https://user-images.githubusercontent.com/1896372/35422442-bdfe3cc8-0216-11e8-9d28-d1fafae00ab0.png">

**Comment by YourMobileGeek** [comment] 2018-02-02 03:29
![screen shot 2018-02-01 at 10 26 34 pm](https://user-images.githubusercontent.com/8063614/35715188-fdd23ff6-079e-11e8-992b-45970f18e420.png)

Was this mainly viewed on desktop or mobile? Was just double checking the specs and resizing the window where the text wasn't covering the MLH logo.

**Comment by andrewsosa** [comment] 2018-02-02 14:19
@YourMobileGeek The issue is at just under the minimum width for desktop, but at a low-height screen; I think @CFarzaneh was viewing it with a 13" non-retina Macbook Pro at default zoom?

**Comment by andrewsosa** [comment] 2018-02-12 13:59
This should be fixed in 27c8217beb6d9286573450254623988f0affcfac.

**Closed by andrewsosa** 2018-02-12 13:59 UTC
Labels: bug, webapp
